development:
  adapter: postgresql
  encoding: unicode
  database: carpool_dev
  pool: 5
  username: rachelminto
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: carpool_test
  pool: 5
  username: rachelminto
  password: